// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsApiHttp "github.com/kuetix/std-http/modules/api/http/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["api/http"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"api/http"+"/"+"http", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "http", Impl: transitionsApiHttp.NewHTTPTransitions()}
		})
	}
}
