// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/pkg/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{
		"api/auth": {
			"jwt": {
				"GenerateToken": {
					Name:        "GenerateToken",
					NumIn:       4,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string", "int"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"userID", "username", "email", "expiresInHours"},
					ReturnNames: []string{"r"},
				},
				"ValidateToken": {
					Name:        "ValidateToken",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"tokenString"},
					ReturnNames: []string{"r"},
				},
				"RefreshToken": {
					Name:        "RefreshToken",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "int"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"tokenString", "expiresInHours"},
					ReturnNames: []string{"r"},
				},
				"ExtractTokenFromHeader": {
					Name:        "ExtractTokenFromHeader",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"authHeader"},
					ReturnNames: []string{"r"},
				},
			},
			"user": {
				"ResetPassword": {
					Name:        "ResetPassword",
					NumIn:       3,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email", "newPassword", "requestingUserEmail"},
					ReturnNames: []string{"r"},
				},
				"RequestPasswordReset": {
					Name:        "RequestPasswordReset",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email"},
					ReturnNames: []string{"r"},
				},
				"Register": {
					Name:        "Register",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email", "password"},
					ReturnNames: []string{"r"},
				},
				"Login": {
					Name:        "Login",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email", "password"},
					ReturnNames: []string{"r"},
				},
				"GetUserByEmail": {
					Name:        "GetUserByEmail",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"email"},
					ReturnNames: []string{"r"},
				},
				"GetAllUsers": {
					Name:        "GetAllUsers",
					NumIn:       0,
					NumOut:      1,
					ArgTypes:    []string{},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{},
					ReturnNames: []string{"r"},
				},
			},
		},
		"api/http": {
			"http": {
				"WorkflowExecutor": {
					Name:        "WorkflowExecutor",
					NumIn:       3,
					NumOut:      1,
					ArgTypes:    []string{"string", "http.ResponseWriter", "*http.Request"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"workflowPath", "w", "r"},
					ReturnNames: []string{"result"},
				},
				"SetupCORS": {
					Name:        "SetupCORS",
					NumIn:       0,
					NumOut:      1,
					ArgTypes:    []string{},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{},
					ReturnNames: []string{"r"},
				},
				"RegisterRoutes": {
					Name:        "RegisterRoutes",
					NumIn:       5,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string", "string", "map[string]*ast.InterfaceType"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"modulesPath", "workflowsPath", "version", "buildTime", "groups"},
					ReturnNames: []string{"result"},
				},
				"StartServer": {
					Name:        "StartServer",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"port"},
					ReturnNames: []string{"result"},
				},
				"ServeFile": {
					Name:        "ServeFile",
					NumIn:       5,
					NumOut:      0,
					ArgTypes:    []string{"http.ResponseWriter", "*http.Request", "string", "string", "string"},
					ReturnTypes: []string{},
					ArgNames:    []string{"w", "r", "path", "contentType", "cacheControl"},
					ReturnNames: []string{},
				},
			},
		},
	})
}
