// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/engine/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{
		"api/http": {
			"http": {
				"WorkflowExecutor": {
					GoModule:    "github.com/kuetix/std-http",
					ModulePath:  "modules",
					FilePath:    "modules/api/http/transitions/http.go",
					Namespace:   "http",
					Class:       "api/http",
					Name:        "WorkflowExecutor",
					NumIn:       4,
					NumOut:      1,
					ArgTypes:    []string{"string", "http.ResponseWriter", "*http.Request", "map[string]interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"workflowPath", "w", "r", "route"},
					ReturnNames: []string{"result"},
				},
				"SetupCORS": {
					GoModule:    "github.com/kuetix/std-http",
					ModulePath:  "modules",
					FilePath:    "modules/api/http/transitions/http.go",
					Namespace:   "http",
					Class:       "api/http",
					Name:        "SetupCORS",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"map[string]interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"options"},
					ReturnNames: []string{"r"},
				},
				"SetNotFoundWorkflow": {
					GoModule:    "github.com/kuetix/std-http",
					ModulePath:  "modules",
					FilePath:    "modules/api/http/transitions/http.go",
					Namespace:   "http",
					Class:       "api/http",
					Name:        "SetNotFoundWorkflow",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"workflowPath"},
					ReturnNames: []string{"result"},
				},
				"RegisterRoutes": {
					GoModule:    "github.com/kuetix/std-http",
					ModulePath:  "modules",
					FilePath:    "modules/api/http/transitions/http.go",
					Namespace:   "http",
					Class:       "api/http",
					Name:        "RegisterRoutes",
					NumIn:       5,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string", "string", "map[string]interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"modulesPath", "workflowsPath", "version", "buildTime", "groups"},
					ReturnNames: []string{"result"},
				},
				"StartServer": {
					GoModule:    "github.com/kuetix/std-http",
					ModulePath:  "modules",
					FilePath:    "modules/api/http/transitions/http.go",
					Namespace:   "http",
					Class:       "api/http",
					Name:        "StartServer",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"port"},
					ReturnNames: []string{"result"},
				},
				"AFileResponse": {
					GoModule:    "github.com/kuetix/std-http",
					ModulePath:  "modules",
					FilePath:    "modules/api/http/transitions/http.go",
					Namespace:   "http",
					Class:       "api/http",
					Name:        "AFileResponse",
					NumIn:       3,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"path", "contentType", "cacheControl"},
					ReturnNames: []string{"result"},
				},
			},
		},
	})
}
